# Generated by Django 2.2.3 on 2019-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20190924_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPokemonEntity',
            new_name='PokemonEntity',
        ),
    ]
