# Generated by Django 2.2.3 on 2019-10-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20190925_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='field',
            new_name='title_en',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
