# Generated by Django 2.2.3 on 2019-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20191004_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
