# Generated by Django 2.2.3 on 2020-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0022_auto_20200105_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка стихии'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='pokemon_entities.PokemonElementType', verbose_name='Стихия покемона'),
        ),
    ]
