# Generated by Django 2.2.3 on 2020-01-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0024_auto_20200105_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Type', verbose_name='Картинка стихии'),
        ),
    ]
