# Generated by Django 2.2.3 on 2020-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_auto_20200106_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='pokemon_entities', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
